name: RTC.APP
version: 1.0.0
description: WebRTC Client
author: Louise van der Lith
repository: https://github.com/louisevanderlith/rtc
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  build_runner: '>=1.6.2 <2.0.0'
  build_web_compilers: